version: 2.1

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install -U pip setuptools virtualenv
            sudo pip3 install awsebcli==3.14.11 --upgrade
      - run: npm install && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./build s3://test-s3-deploy-reco
      - run:
          name: Invalidate Cloudfront
          command: aws cloudfront create-invalidation --distribution-id E2CC3KTIR6ZBJ3 --paths "/*"

workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          context:
            - Test
          requires:
            - build
